---
- name: Administrator Playbook - Full Role Access
  hosts: app_servers
  gather_facts: yes

  vars_files:
    - "{{ app_vars }}"

  roles:
    - role: common
    - role: app-deploy
    - role: app-restart
    - role: logs-collect
    - role: db-ops
    - role: monitoring-agent
    - role: patching
    - role: backup
