---
- name: Check application HTTP endpoint
  uri:
    url: "{{ healthcheck_url }}"
    method: GET
    status_code: 200
  register: http_check

- name: Print HTTP health check result
  debug:
    msg: "Application responded with status {{ http_check.status }}"

- name: Check database connectivity (MySQL example)
  community.mysql.mysql_info:
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
  register: db_check
  when: db_host is defined

- name: Print DB health check result
  debug:
    msg: "Database connection successful: {{ db_check is defined }}"
  when: db_host is defined
