
---
all:
  children:
    linux:
      hosts:
        localhost:
          ansible_connection: local
        linux-test:
          ansible_host: 192.168.56.101
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    windows:
      hosts:
        windows-test:
          ansible_host: 192.168.56.102
          ansible_user: Administrator
          ansible_password: "YourPasswordHere"
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_port: 5985
