
---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: "python:3.12-slim"
    privileged: true
    command: /sbin/init
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: ansible
